import type { Metadata } from "next";
import {Inter , Calistoga } from 'next/font/google'
//import localFont from "next/font/local";
import localFont from "next/font/local"
import "./globals.css";
import {twMerge} from "tailwind-merge";

//utiliza esta confuguracion para incorporar futura blont de fulbo pago
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

const futuraBold = localFont({
    src: "./fonts/FuturaLT-Bold.woff",
  variable: "--font-futura",
 
});


const inter = Inter({
  subsets:['latin'],
  variable:'--font-sans'
});
const calistoga = Calistoga({
  subsets:['latin'],
  variable:'--font-serif',
  weight:["400"]
});

export const metadata: Metadata = {
  title: "Imora-dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={twMerge(inter.variable,calistoga.variable,futuraBold.variable,'bg-gray-900 text-white antialiased font-sans')}
      >
        {children}
      </body>
    </html>
  );
}
